### ISSUE TITLE
Do you have the sample code for DANN in keras?.

### ISSUE THREAD

**Issue by bbdamodaran** [michetonu/gradient_inversion_keras_tf#2]
I implemented DANN in keras using your gradient reversal layer, but I don't good results. It will be nice, if could share your code

thanks

**Comment by michetonu** [comment]
@bbdamodaran super late, but I only recently got around to put the code for the whole model online. Here it is: https://github.com/michetonu/DA-RNN_manoeuver_anticipation

**Comment by michetonu** [comment]
My best advice is to try and optimize the parameter lambda – i.e. how much weight to give to each branch of the model. It is still not guaranteed to work for all data and problems though!
