### ISSUE TITLE
error in build 

### ISSUE THREAD

**Issue by senjed** [michetonu/gradient_inversion_keras_tf#8]
I get the following error when I call flip_layer = Flip(X). I changed self.trainable_weights to self._trainable_weights in build but that does not solve the problem. 

AttributeError: Can't set the attribute "trainable_weights", likely because it conflicts with an existing read-only @property of the object. Please choose a different name.

**Comment by michetonu** [comment]
See https://github.com/michetonu/gradient_reversal_keras_tf/issues/9
